package com.demo.bean;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.AccountId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.UserName
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Password
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Phone
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Email
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Address
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Role
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.AccountId
     *
     * @return the value of account.AccountId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.AccountId
     *
     * @param accountId the value for account.AccountId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.UserName
     *
     * @return the value of account.UserName
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.UserName
     *
     * @param userName the value for account.UserName
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Password
     *
     * @return the value of account.Password
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Password
     *
     * @param password the value for account.Password
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Phone
     *
     * @return the value of account.Phone
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Phone
     *
     * @param phone the value for account.Phone
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Email
     *
     * @return the value of account.Email
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Email
     *
     * @param email the value for account.Email
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Address
     *
     * @return the value of account.Address
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Address
     *
     * @param address the value for account.Address
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Role
     *
     * @return the value of account.Role
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Role
     *
     * @param role the value for account.Role
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setRole(String role) {
        this.role = role;
    }
}