package com.demo.bean;

public class AccounttestKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounttest.AccountId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounttest.AccountTestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    private Integer accountTestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounttest.TestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    private Integer testId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounttest.AccountId
     *
     * @return the value of accounttest.AccountId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounttest.AccountId
     *
     * @param accountId the value for accounttest.AccountId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounttest.AccountTestId
     *
     * @return the value of accounttest.AccountTestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public Integer getAccountTestId() {
        return accountTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounttest.AccountTestId
     *
     * @param accountTestId the value for accounttest.AccountTestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public void setAccountTestId(Integer accountTestId) {
        this.accountTestId = accountTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounttest.TestId
     *
     * @return the value of accounttest.TestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounttest.TestId
     *
     * @param testId the value for accounttest.TestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }
}