package com.demo.bean;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.QuestionId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.QuestionContent
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private String questionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.TestId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.Point
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.QuestionId
     *
     * @return the value of question.QuestionId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.QuestionId
     *
     * @param questionId the value for question.QuestionId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.QuestionContent
     *
     * @return the value of question.QuestionContent
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.QuestionContent
     *
     * @param questionContent the value for question.QuestionContent
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.TestId
     *
     * @return the value of question.TestId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.TestId
     *
     * @param testId the value for question.TestId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.Point
     *
     * @return the value of question.Point
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.Point
     *
     * @param point the value for question.Point
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}