package com.demo.bean;

public class QuestionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.QuestionId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.TestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    private Integer testId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.QuestionId
     *
     * @return the value of question.QuestionId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.QuestionId
     *
     * @param questionId the value for question.QuestionId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.TestId
     *
     * @return the value of question.TestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.TestId
     *
     * @param testId the value for question.TestId
     *
     * @mbggenerated Mon May 09 11:14:15 ICT 2016
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }
}