package com.demo.bean;

public class TestresultKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.AccountId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.TestResultId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    private Integer testResultId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.AccountId
     *
     * @return the value of testresult.AccountId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.AccountId
     *
     * @param accountId the value for testresult.AccountId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.TestResultId
     *
     * @return the value of testresult.TestResultId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public Integer getTestResultId() {
        return testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.TestResultId
     *
     * @param testResultId the value for testresult.TestResultId
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    public void setTestResultId(Integer testResultId) {
        this.testResultId = testResultId;
    }
}