package com.demo.dao;

import java.util.List;
import java.util.Map;

import com.demo.bean.Question;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    Question selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu May 12 15:13:51 ICT 2016
     */
    int updateByPrimaryKey(Question record);

    /**
     * Select all pagging.
     *
     * @param map
     * @return List<Question>
     */
    List<Question> sellectAllPagging(Map<String,Object> map);

    /**
     * Get all count.
     *
     * @return count
     */
    int getAllCount();
}